import React, { useState, useEffect, useRef } from 'react'
import styles from './Order.module.css'
import Footer from "../../../Footer/Footer"
import axios from 'axios';
import Navbar from '../../../../Components/Navbar/nav';
import Link from 'next/link'
import Router from 'next/router'
import Image from 'next/image'
import { FiChevronLeft,FiChevronRight } from 'react-icons/fi'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import Pro from "../../../../img/avatar3.png";
export default function ProductPage(){
    const [ listProduct, setListProduct ] = useState([])
    const [ allProduct, setAllProduct ] = useState([])
    const [ currentPage, setCurrentPage ] = useState(1)
    const [ Max_Product_Per_Page, setMax_Product_Per_Page ] = useState(10)
    const [ maxPage, setMaxPage ] = useState(0)
    const [email, setEmail] = useState();
    const [userProfile, setUserProfile] = useState([]);
    useEffect(() => {
        if (localStorage.getItem("Email")) {
          
          setEmail(localStorage.getItem("Email"));
    
        }
      }, []);  
   

      const getUserProfile = async () => {
        const URL =
          "http://localhost:3000/api/allProduct?Email=" +
          localStorage.getItem("Email");
        await axios
          .get(URL)
          .then((result) => {
            console.log(result);
            setUserProfile([result.data]);
          })
          .catch((err) => {
            // Localhost ios issus
            console.log(err);
            axios
              .get("/api/kycClick")
              .then((result) => {
                // setUserProfile( result.data )
                console.log([result.data]);
                setUserProfile([result.data]);
              })
              .catch((err) => {
                setUserProfile([{ img: "", Email: err.message }]);
              });
          });
      };
      useEffect(() => {
        getUserProfile();
      }, []);
    
    return (
        
        <div>
            <Head>
                <title>Ject Jobe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
        <div className={styles.container}>
        <div className={styles.contentContainer}>
            <div className={styles.row}>
                <div className={styles.col}>
                    <div id="content" className={styles.content}>
                        <div className={styles.profile}>
                        <div className={styles.profile_header}>
                            <div className={styles.profile_header_cover}></div>
                            <div className={styles.profile_header_content}>
                                <div className={styles.profile_header_img}>
                                {(userProfile[0] === undefined) && 
                           
                           <div>
                             <Image
                               src={Pro}
                               alt="Profile"
                               objectFit="cover"
                             />
                           </div>
                         }
                         {userProfile[0] != undefined &&
                           userProfile.map((element) => {
                             console.log(element.img);
                             return (
                               <div className={styles.Image}>
                                 <Image
                                   src={element[0].img}
                                   alt="Profile"
                                   objectFit="cover"
                                   width="105px"
                                   height="109px"
                                 />
                                 
                               </div>
                               
                             );
                           })}
                                </div>
                                {userProfile[0] != undefined &&
                          userProfile.map((element) => {
                            console.log(element[0].fullName);
                            return (
                              <div className={styles.profile_header_info}>
                                <h4 class="m-t-10 m-b-5">
                                  ชื่อร้าน : {element[0].productName}
                                </h4>
                                <p class="m-b-10">
                                  สร้างเมื่อ : {element[0].addDate}
                                </p>
                                <p class="m-b-10">
                                  Rate : 
                                </p>
                                
                              </div>
                            );
                          })}
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            
           
        
        </div>
        </div>
        
    )

}