import Head from 'next/head'
// import Image from 'next/image'
import styles1 from '../styles/Home.module.css'
import Navbar from '../Components/Navbar/nav'
import SideBar from './SideNavBar/sideNav'
import { BsCart2 } from 'react-icons/bs';
import Link from 'next/link';
import Foot from "./Footer/Footer";
import { useDispatch } from "react-redux";
import { increment } from "../slices/counterSlice";
import ProductPage from '../Components/ProductList/index';


export default function index() {
  
  return (  
    <div >
      <Head>
        <title>Ject Jobe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <SideBar/>

       <ProductPage/>
       <Foot/>
    </div>
 
  )
  }
