import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Navbar from '../Components/Navbar/nav'

export default function index() {
  return (
    <div >
      <Head>
        <title>Ject Jobe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>

    </div>
  )
}
